version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx-proxy
    ports:
     - "80:80"
     - "443:443"
    links:
      - jupyterhub

  jupyterhub:
    container_name: jupyterhub
    build: ./jupyter-hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  data-nfs:
    container_name: data-nfs
    build: ./data-nfs
    volumes:
      - /tmp/schrott/home:/exports/home
    cap_add:
      - SYS_ADMIN
    links:
      - jupyterhub
